{
 "title": "Capacity Planning",
 "tags": [
  "capacity",
  "sre",
  "postgres"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Throughput by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=~\"app-a|app-b|app-c\"}[5m])) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "p95 Latency by Service (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_server_duration_milliseconds_bucket{exported_job=~\"app-a|app-b|app-c\"}[5m])) by (le, exported_job))",
     "legendFormat": "{{exported_job}} p95"
    }
   ]
  },
  {
   "title": "Error Ratio by Tier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(worker_errors_total[5m])) or vector(0)) / clamp_min(sum(rate(worker_requests_total[5m])), 0.0001)",
     "legendFormat": "app-b error ratio"
    },
    {
     "expr": "(sum(rate(data_errors_total[5m])) or vector(0)) / clamp_min(sum(rate(data_requests_total[5m])), 0.0001)",
     "legendFormat": "app-c error ratio"
    },
    {
     "expr": "(sum(rate(demo_errors_total[5m])) or vector(0)) / clamp_min(sum(rate(demo_requests_total[5m])), 0.0001)",
     "legendFormat": "app-a error ratio"
    }
   ]
  },
  {
   "title": "Event Loop Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_utilization_ratio{exported_job=~\"app-a|app-b|app-c\"}) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "DB Query p95 (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(db_query_duration_ms_bucket[5m])) by (le))",
     "legendFormat": "db query p95"
    }
   ]
  },
  {
   "title": "DB Saturation Signals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"srelab\"}",
     "legendFormat": "postgres backends"
    },
    {
     "expr": "sum(increase(db_pool_hold_total[5m]))",
     "legendFormat": "held connections"
    }
   ]
  }
 ]
}