{
 "title": "Database Health",
 "tags": [
  "database",
  "postgres",
  "sre"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Postgres Exporter Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "App-C DB Query p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_query_duration_ms_bucket[5m])) by (le))",
     "legendFormat": "db query p95"
    }
   ]
  },
  {
   "title": "App-C DB Query Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(db_queries_total[5m]))",
     "legendFormat": "queries"
    },
    {
     "expr": "sum(increase(db_query_errors_total[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Postgres Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"srelab\"}",
     "legendFormat": "active backends"
    }
   ]
  },
  {
   "title": "Postgres Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"srelab\"}[5m])",
     "legendFormat": "commits/sec"
    }
   ]
  }
 ]
}